
        // This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


        

        

        class Player  {
                final String username;
final String avatarColor;
final int score;

                const Player({required this.username ,required this.avatarColor ,required this.score ,});

                
                

                
        @override
        int get hashCode => username.hashCode^avatarColor.hashCode^score.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is Player &&
                runtimeType == other.runtimeType
                && username == other.username&& avatarColor == other.avatarColor&& score == other.score;
        
            }
        