// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.34.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Question {
  final int questionId;
  final String question;
  final List<(int, String)> answers;

  const Question({
    required this.questionId,
    required this.question,
    required this.answers,
  });

  @override
  int get hashCode =>
      questionId.hashCode ^ question.hashCode ^ answers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Question &&
          runtimeType == other.runtimeType &&
          questionId == other.questionId &&
          question == other.question &&
          answers == other.answers;
}
