// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class UserData {
  final String username;
  final String email;
  final String address;
  final String phoneNumber;
  final String birthday;
  final String avatarColor;
  final DateTime memberSince;

  const UserData({
    required this.username,
    required this.email,
    required this.address,
    required this.phoneNumber,
    required this.birthday,
    required this.avatarColor,
    required this.memberSince,
  });

  @override
  int get hashCode =>
      username.hashCode ^
      email.hashCode ^
      address.hashCode ^
      phoneNumber.hashCode ^
      birthday.hashCode ^
      avatarColor.hashCode ^
      memberSince.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserData &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          email == other.email &&
          address == other.address &&
          phoneNumber == other.phoneNumber &&
          birthday == other.birthday &&
          avatarColor == other.avatarColor &&
          memberSince == other.memberSince;
}

class UserDataAndStatistics {
  final UserData userData;
  final UserStatistics userStatistics;

  const UserDataAndStatistics({
    required this.userData,
    required this.userStatistics,
  });

  @override
  int get hashCode => userData.hashCode ^ userStatistics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserDataAndStatistics &&
          runtimeType == other.runtimeType &&
          userData == other.userData &&
          userStatistics == other.userStatistics;
}

class UserStatistics {
  final int? averageAnswerTime;
  final int correctAnswers;
  final int wrongAnswers;
  final int totalAnswers;
  final int totalGames;
  final int score;

  const UserStatistics({
    this.averageAnswerTime,
    required this.correctAnswers,
    required this.wrongAnswers,
    required this.totalAnswers,
    required this.totalGames,
    required this.score,
  });

  @override
  int get hashCode =>
      averageAnswerTime.hashCode ^
      correctAnswers.hashCode ^
      wrongAnswers.hashCode ^
      totalAnswers.hashCode ^
      totalGames.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserStatistics &&
          runtimeType == other.runtimeType &&
          averageAnswerTime == other.averageAnswerTime &&
          correctAnswers == other.correctAnswers &&
          wrongAnswers == other.wrongAnswers &&
          totalAnswers == other.totalAnswers &&
          totalGames == other.totalGames &&
          score == other.score;
}
