// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class UserData {
  final String username;
  final String email;
  final String address;
  final String phoneNumber;
  final String birthday;
  final String avatarColor;
  final DateTime memberSince;

  const UserData({
    required this.username,
    required this.email,
    required this.address,
    required this.phoneNumber,
    required this.birthday,
    required this.avatarColor,
    required this.memberSince,
  });

  @override
  int get hashCode =>
      username.hashCode ^
      email.hashCode ^
      address.hashCode ^
      phoneNumber.hashCode ^
      birthday.hashCode ^
      avatarColor.hashCode ^
      memberSince.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserData &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          email == other.email &&
          address == other.address &&
          phoneNumber == other.phoneNumber &&
          birthday == other.birthday &&
          avatarColor == other.avatarColor &&
          memberSince == other.memberSince;
}
