name: your_flutter_app_name
description: A Flutter app for login and signup pages
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  dynamic_color: ^1.7.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/illustration.png
    - assets/background.png
    - assets/logo.png
    - assets/question1.png

  uses-material-design: true

