name: trivia
description: "A Trivia Game By Shahar Yogev & Yuval Bar"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  side_sheet_material3: ^0.0.2
  awesome_side_sheet: ^0.0.3
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  dynamic_color: ^1.7.0
  rust_lib_trivia:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.33
  freezed_annotation: ^2.4.1
  ffi: ^2.1.2
  shared_preferences: ^2.2.3
  bitsdojo_window: ^0.1.6
  flutter_material_color_picker: ^1.2.0
  skeletonizer: ^1.1.2+1
  flutter_gradient_animation_text: ^1.0.2
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.9
  ffigen: ^12.0.0

flutter:
  uses-material-design: true


