name: Release

on:
  push:
    tags:
      - 'v*'


jobs:
  android-and-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install cargo-expand
      - run: cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml

      - run: flutter_rust_bridge_codegen generate
      - run: flutter pub get
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt install rpm patchelf
      - run: dart pub global activate flutter_distributor
      - run: flutter_distributor release --name=dev --jobs=release-linux-rpm
      - run: flutter_distributor release --name=dev --jobs=release-linux-deb
      - run: flutter_distributor release --name=dev --jobs=release-android
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-rpm-deb
          # every artifact that ends with .apk and .rpm
          path: |
            ./dist/**/*.apk
            ./dist/**/*.rpm
            ./dist/**/*.deb
          if-no-files-found: error
          retention-days: 1 # delete artifacts after 1 day
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter_rust_bridge_codegen generate
      - run: flutter pub get
      - run: dart pub global activate flutter_distributor
      - run: flutter_distributor release --name=dev --jobs=release-windows
      - run: flutter build windows --release
      - run: ls -la -R dist
  release:
    needs: [android-and-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: apk-rpm-deb
          path: artifacts
          github_token: ${{ secrets.TOKEN }}
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/**/*.apk,artifacts/**/*.rpm,artifacts/**/*.deb"
          token: ${{ secrets.TOKEN }}
          commit: ${{ github.sha }}
